---
title: "Resources"
output: html_document
---

<style>
.title {
    display: none;
}

.header {
  background-color: #ECF0F1;
  padding: 0px;
  margin: 0px;
  text-align: center;
  width: 100%;
}

</style>


<h1 style="text-align: center; margin-top: 5px; margin-bottom: 16.5px;">Interested in joining the lab?</h1>

<div class="header">
  <p>Our lab celebrates curiosity, encourages collaboration, and cultivates both intellectual playfulness and rigor.<br>
We work to create an environment that is inclusive and anti-racist — a lab where people can thrive, regardless of background, identity, or ability. That includes Black, Indigenous, and People of Color, first-generation college students, women, LGBTQ+ folk, people with disabilities, people from any country and with any immigration status, people belonging to groups that have been historically underrepresented in academia or cognitive science, and everybody else. </p>
</div>

<h3>Research Assistants</h3>
<p style="font-size: 16px; padding-left: 2px;"> Looking to become a Research Assistant? Fill out our application [here](https://forms.gle/6AkBRiceyc54aB378)!</p>
<p style="padding-left: 2px">Enthusiasm required but prior research experience is not! </p>
<p style="padding-left: 2px">Note: We are currently at full capacity. However, we leave our application open year round so it can be filled out at any time. We typically review applications and reach out around the start of each semester.</p>

<h3>Graduate Students</h3>
<p style="font-size: 16px; padding-left: 2px;">We accept graduate students through the Department of [Cognitive and Information Sciences](https://cogsci.ucmerced.edu/node/551).</p>
<p style="padding-left: 2px">Potential applicants are encouraged to contact Tyler by [email](https://marghetislab.github.io/contact.html). Please include a brief description of yourself and your research interests, and attach your CV or resume.</p>

<h3>Postdoctoral Scholars</h3>
<p style="padding-left: 2px"> While we do not currently have funding for postdoctoral scholars, interested researchers are encouraged to contact Prof. Tyler Marghetis by email to discuss possibilities.</p>

<h3>Other Resources</h3>
<p style="font-size: 16px; padding-left: 2px;"> Request a Letter of Recommendation from Dr. Marghetis [here](https://forms.gle/ZRgDLkYU8yTdyATJ8)</p>
<p style="padding-left: 2px">Please refrain from requesting a letter if you have not had direct interactions with Prof. Tyler Marghetis in the past. We want you to have the best recommendations possible and will be unable to provide you with a quality, personalized letter without knowledge of your background and experiences.</p>
</body>